### ISSUE TITLE
camelcase npm module - Possible code improvement

### ISSUE THREAD

**Issue by kalmanh** [dguo/broker-scribe#1]
Take a look at [camelcase](https://github.com/sindresorhus/camelcase)

You can then shorten your `mapHeaders` to just this below

```javascript
function mapHeaders({header, index}) {
    const neededColumns = [
        'Description', 'Date Acquired', 'Date Sold', 'Gross Proceeds',
        'Cost or Other Basis', 'Reporting Category', 'Wash Sale Loss Disallowed',
        'Federal Income Tax Withheld'
    ];

    return neededColumns.includes(header) ? camelCase(header) : null;
}
```

**Comment by dguo** [comment]
I considered doing that when I wrote it, but I wanted to specify the columns anyway to be explicit about which ones would be available to the program. Once I did that, adding another line for each one for the case conversion was such a small thing that it didn't seem worth it to add another dependency.

Thanks for the suggestion though!
